version: '3'

services:
        db:
          restart: always
          image: mysql:5.6
          environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: gokopen
            MYSQL_USER: gokopen
            MYSQL_PASSWORD: gokopen
            TZ: Europe/Stockholm
          ports:
            - 3306:3306
          volumes:
           - ./db:/docker-entrypoint-initdb.d
           - ./db/data:/var/lib/mysql

        web:
          restart: always
          # image: tomcat:8.5.43-jdk8-openjdk
          image: tomcat:8.5.82-jre8
          environment:
            TZ: Europe/Stockholm
          ports:
           - 80:8080
          volumes:
           - ./webapps:/usr/local/tomcat/webapps
          links:
            - db
          depends_on:
            - db
 
